# Generated by Django 5.2.4 on 2025-07-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Код (slug)")),
            ],
            options={"verbose_name": "Меню", "verbose_name_plural": "Меню",},
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "url",
                    models.CharField(blank=True, max_length=255, verbose_name="URL"),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Named url"
                    ),
                ),
                (
                    "named_args",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Named args (JSON)"
                    ),
                ),
                (
                    "named_kwargs",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Named kwargs (JSON)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menus.menu",
                        verbose_name="Меню",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menus.menuitem",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["menu", "parent"], name="menus_menui_menu_id_5ea954_idx"
                    )
                ],
            },
        ),
    ]
