name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # healthcheck for postgres
        options: >-
          --health-cmd "pg_isready -U postgres -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure Django settings
        run: |
          echo "DEBUG=True" >> .env
          echo "SECRET_KEY=test-secret-key" >> .env
          echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
          # Use sqlite for tests by default
          echo "DATABASE_URL=sqlite:///db.sqlite3" >> .env

      - name: Run migrations
        run: python manage.py migrate --no-input

      - name: Run tests
        run: |
          # Run Django tests
          python manage.py test
          # If using pytest:
          if [ -f pytest.ini ] || [ -f pyproject.toml ]; then pytest; fi
